/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme/remote-claw.ts
 * Command: astryx theme build app/theme/remote-claw.ts
 */

/// <reference path="./remote-claw.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const remoteClawTheme: DefinedTheme;
