/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme/remote-claw.ts
 * Command: astryx theme build app/theme/remote-claw.ts
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
