"use client";

import type { ThemeMode } from "@astryxdesign/core/theme";
import { Theme } from "@astryxdesign/core/theme";
import { createContext, type ReactNode, useCallback, useContext, useMemo, useState } from "react";
import { remoteClawTheme } from "./theme/built/remote-claw.js";
import { THEME_COOKIE } from "./theme-mode";

interface ThemeModeContextValue {
  /** The active preference: "system" follows the OS, "light"/"dark" force a surface. */
  mode: ThemeMode;
  /** Set the preference — updates <Theme> live AND persists to the rc-theme cookie for next load. */
  setMode: (mode: ThemeMode) => void;
}

const ThemeModeContext = createContext<ThemeModeContextValue | null>(null);

/** Read the colour-mode preference + setter. Throws outside <Providers> so a stray consumer is loud. */
export function useThemeMode(): ThemeModeContextValue {
  const ctx = useContext(ThemeModeContext);
  if (ctx === null) throw new Error("useThemeMode must be used within <Providers>");
  return ctx;
}

/** Astryx's theme provider, pinned to the viewer's brand theme, with a user-switchable colour mode.
 *
 *  `initialMode` comes from the server layout, which read it from the rc-theme cookie. Seeding React
 *  state with it means the FIRST client render matches the server (the <Theme> wrapper emits a per-mode
 *  `color-scheme` class, so a server/client mode disagreement would be a hydration mismatch), and the
 *  layout has already stamped the matching `data-theme` on <html> for a flash-free first paint.
 *
 *  Default is "system": the viewer follows the OS unless the user overrides it via the topbar toggle.
 *  (It shipped dark-only for a long time — see git history — until the theme's light half, present in
 *  app/theme/remote-claw.ts all along, was verified and turned on.)
 *
 *  The theme object is the BUILT one (app/theme/built/, generated by `pnpm run theme:build`): it carries
 *  `__built: true`, which tells <Theme> to skip runtime <style> injection because the compiled
 *  remote-claw.css — already imported from globals.css — carries the (light-dark) tokens on first paint.
 *
 *  NOTE the explicit `.js` on the import. The built module sits in `theme/built/` rather than beside its
 *  `remote-claw.ts` source precisely so this resolves unambiguously: next.config's
 *  `extensionAlias: { ".js": [".ts", ".tsx", ".js"] }` (there for clawsec's raw-TS exports) tries `.ts`
 *  FIRST, so a `remote-claw.js` sitting next to `remote-claw.ts` would silently resolve to the SOURCE
 *  theme — the runtime-injection path — instead of the built one. No such twin exists under built/.
 */
export function Providers({
  children,
  initialMode = "system",
}: {
  children: ReactNode;
  initialMode?: ThemeMode;
}) {
  const [mode, setModeState] = useState<ThemeMode>(initialMode);

  const setMode = useCallback((next: ThemeMode) => {
    setModeState(next);
    // Persist for the next load. A cookie (not localStorage) so the server layout can read it and render
    // the right data-theme on first paint. SameSite=Lax + a year; no secret, so no other flags needed.
    // document.cookie is the portable write path — WebKit (which the app-e2e suite runs) lacks Cookie Store.
    // biome-ignore lint/suspicious/noDocumentCookie: portable write path; WebKit lacks the Cookie Store API.
    document.cookie = `${THEME_COOKIE}=${next}; path=/; max-age=31536000; samesite=lax`;
  }, []);

  const value = useMemo<ThemeModeContextValue>(() => ({ mode, setMode }), [mode, setMode]);

  return (
    <ThemeModeContext.Provider value={value}>
      <Theme theme={remoteClawTheme} mode={mode}>
        {children}
      </Theme>
    </ThemeModeContext.Provider>
  );
}
