"use client";

import { Theme } from "@astryxdesign/core/theme";
import type { ReactNode } from "react";
import { remoteClawTheme } from "./theme/built/remote-claw.js";

/** Astryx's theme provider, pinned to the viewer's brand theme and to DARK.
 *
 *  `mode="dark"` rather than the default `"system"` on purpose: the viewer is a single dark surface (it's
 *  a console you open on a phone to steer a machine), the palette in app/theme/remote-claw.ts only has a
 *  ship-quality dark half, and `"system"` would hand a light-mode user an untested second UI. It also
 *  keeps SSR deterministic — `"system"` resolves from a media query that the server can't read, so the
 *  first paint would have to guess.
 *
 *  The theme object is the BUILT one (app/theme/built/, generated by `pnpm run theme:build`): it carries
 *  `__built: true`, which tells <Theme> to skip runtime <style> injection because the compiled
 *  remote-claw.css — already imported from globals.css — carries the tokens on first paint.
 *
 *  NOTE the explicit `.js` on the import. The built module sits in `theme/built/` rather than beside its
 *  `remote-claw.ts` source precisely so this resolves unambiguously: next.config's
 *  `extensionAlias: { ".js": [".ts", ".tsx", ".js"] }` (there for clawsec's raw-TS exports) tries `.ts`
 *  FIRST, so a `remote-claw.js` sitting next to `remote-claw.ts` would silently resolve to the SOURCE
 *  theme — the runtime-injection path — instead of the built one. No such twin exists under built/.
 */
export function Providers({ children }: { children: ReactNode }) {
  return (
    <Theme theme={remoteClawTheme} mode="dark">
      {children}
    </Theme>
  );
}
