// @remote-claw/clawsec — the crypto core. Public surface grows one unit per PR.

export {
  A1_BROKER_CIPHERTEXT_LIMIT_BYTES,
  A1_BROKER_DEFAULT_READ_FRAMES,
  A1_BROKER_GENERATION_FRAME_CAP,
  A1_BROKER_GENERATION_MANIFEST_DOMAIN,
  A1_BROKER_MAX_PARTS,
  A1_BROKER_MAX_RAW_FRAME_BYTES,
  A1_BROKER_MAX_READ_ENCODED_BYTES,
  A1_BROKER_MAX_READ_FRAMES,
  type A1BrokerCanonicalFrameV1,
  A1BrokerContractError,
  type A1BrokerContractErrorReason,
  type A1BrokerEnsureRouteReceiptV1,
  type A1BrokerGenerationManifestInputV1,
  type A1BrokerPublishReceiptV1,
  type A1BrokerReadFrameV1,
  type A1BrokerReadPageV1,
  type A1BrokerRouteDescriptorV1,
  type A1BrokerTransportCollisionV1,
  a1BrokerGenerationManifestDigest,
  BROKER_BACKEND_CAPABILITIES_SCHEMA_ID,
  type BrokerBackendCapabilitiesV1,
  type BrokerChannelCursorV1,
  type BrokerChannelGenerationRecordV1,
  type BrokerReadPositionV1,
  brokerBackendCapabilitiesDigest,
  canonicalA1BrokerGenerationManifestV1,
  canonicalBrokerBackendCapabilitiesV1,
  encodeA1BrokerEnsureRouteReceiptV1,
  encodeA1BrokerPublishReceiptV1,
  encodeA1BrokerReadPageV1,
  encodeA1BrokerRouteDescriptorV1,
  encodeA1BrokerTransportCollisionV1,
  encodeBrokerChannelCursorV1,
  encodeBrokerChannelGenerationRecordV1,
  encodeBrokerReadPositionV1,
  parseA1BrokerCanonicalFrameV1,
  parseA1BrokerEnsureRouteReceiptV1,
  parseA1BrokerOrigin,
  parseA1BrokerPublishReceiptV1,
  parseA1BrokerReadPageV1,
  parseA1BrokerRouteDescriptorV1,
  parseA1BrokerRouteStoreInstanceId,
  parseA1BrokerTransportCollisionV1,
  parseBrokerBackendCapabilitiesV1,
  parseBrokerChannelCursorV1,
  parseBrokerChannelGenerationRecordV1,
  parseBrokerReadPositionV1,
  SELECTED_A1_BROKER_BACKEND_CAPABILITIES_V1,
} from "./a1-broker.js";
export {
  A1CertificateError,
  type A1CertificateErrorReason,
  type A1Ed25519PublicKeyBinding,
  canonicalNativeRootPayload,
  canonicalServerScopeCertificatePayload,
  canonicalViewerOnboardingKeyAttestationPayload,
  encodeNativeRootCertificatePayload,
  encodeServerScopeCertificatePayload,
  encodeViewerOnboardingKeyAttestationPayload,
  NATIVE_ROOT_CERTIFICATE_SCHEMA_ID,
  NATIVE_ROOT_CERTIFICATE_SIGNED_DOMAIN,
  NATIVE_ROOT_MAX_TTL_MS,
  type NativeRootCanonicalPayloadInput,
  type NativeRootCertificate,
  nativeRootCanonicalPayloadDigest,
  nativeRootCertificatePayloadDigest,
  nativeRootCertificateSignedRecordDigest,
  parseA1Ed25519PublicKeyBinding,
  parseNativeRootCanonicalPayloadInput,
  parseNativeRootCertificate,
  parseServerScopeCertificateCanonicalPayloadInput,
  parseServerScopeCertificateRecord,
  parseViewerOnboardingKeyAttestationCanonicalPayloadInput,
  parseViewerOnboardingKeyAttestationV1,
  SERVER_SCOPE_CERTIFICATE_SCHEMA_ID,
  SERVER_SCOPE_CERTIFICATE_SIGNED_DOMAIN,
  type ServerScopeCertificateCanonicalPayloadInput,
  type ServerScopeCertificateRecord,
  serverScopeCertificateCanonicalPayloadDigest,
  serverScopeCertificatePayloadDigest,
  serverScopeCertificateSignedRecordDigest,
  serverScopeCertificateSignerKeyGeneration,
  VIEWER_ONBOARDING_KEY_COMMITMENT_DOMAIN,
  VIEWER_ONBOARDING_KEYS_SCHEMA_ID,
  VIEWER_ONBOARDING_KEYS_SIGNED_DOMAIN,
  type ViewerOnboardingKeyAttestationCanonicalPayloadInput,
  type ViewerOnboardingKeyAttestationV1,
  type ViewerOnboardingKeyCommitments,
  type ViewerOnboardingKeyLabel,
  type ViewerOnboardingOperationalKeys,
  verifyNativeRootCertificate,
  verifyServerScopeCertificate,
  verifyViewerOnboardingKeyAttestation,
  viewerOnboardingKeyAttestationCanonicalPayloadDigest,
  viewerOnboardingKeyAttestationPayloadDigest,
  viewerOnboardingKeyAttestationSignedRecordDigest,
  viewerOnboardingKeyCommitment,
  viewerOnboardingKeyCommitments,
} from "./a1-certificates.js";
export {
  A1_INGRESS_ASSEMBLY_DEADLINE_MS,
  A1_INGRESS_LOOKAHEAD_MAX_BYTES,
  A1_INGRESS_LOOKAHEAD_MAX_FRAMES,
  A1_INGRESS_MAX_CANDIDATES_PER_RESULT,
  A1_INGRESS_MAX_OPENED_PART_BYTES,
  A1_INGRESS_MAX_PARTS,
  A1_INGRESS_MAX_REASSEMBLED_PLAINTEXT_BYTES,
  A1_INGRESS_MAX_RETAINED_PLAINTEXT_BYTES_GLOBAL,
  A1_INGRESS_MAX_RETAINED_PLAINTEXT_BYTES_PER_IDENTITY,
  A1_INGRESS_MAX_RETAINED_PLAINTEXT_BYTES_PER_ROUTE,
  A1_INGRESS_MAX_UNRESOLVED_RESULTS_PER_ROUTE,
  A1_INGRESS_NEW_CHAT_PAYLOAD_SCHEMA_ID,
  A1_INGRESS_SCHEDULER_CONCURRENCY,
  A1_INGRESS_USER_PAYLOAD_SCHEMA_ID,
  A1IngressContractError,
  type A1IngressContractErrorReason,
  type A1IngressNewChatPayloadV1,
  type A1IngressRoute,
  type A1IngressUserPayloadV1,
  type A1SelectedInboundPayload,
  a1IngressAuthenticatedPartDigest,
  a1IngressCanonicalMessageDigest,
  a1IngressSourceEventFingerprint,
  a1IngressStableLogicalHeaderDigest,
  assertA1WebSourceNamespaceId,
  canonicalA1ChannelPositionObservationPreimage,
  canonicalA1IngressObservationPreimage,
  canonicalA1IngressSourceEventFingerprintPreimage,
  canonicalA1IngressStableLogicalHeader,
  canonicalA1StableSemanticResultPreimage,
  canonicalA1WebSourceNamespacePreimage,
  compareA1BrokerChannelCursors,
  deriveA1ChannelPositionObservationId,
  deriveA1IngressObservationId,
  deriveA1StableSemanticResultId,
  deriveA1WebSourceNamespaceId,
  encodeA1IngressNewChatPayloadV1,
  encodeA1IngressNewChatPayloadV1Bytes,
  encodeA1IngressUserPayloadV1,
  encodeA1IngressUserPayloadV1Bytes,
  isA1BrokerChannelCursorSuccessor,
  parseA1IngressNewChatPayloadV1,
  parseA1IngressUserPayloadV1,
  parseSelectedA1InboundPayload,
  successorA1BrokerChannelCursor,
} from "./a1-ingress.js";
export {
  canonicalViewerOnboardingBundleBytes,
  formatViewerOnboardingBundle,
  parseViewerOnboardingBundleV2,
  parseViewerOnboardingBundleWire,
  type VerifyViewerOnboardingBundleOptions,
  VIEWER_ONBOARDING_BUNDLE_DOMAIN,
  VIEWER_ONBOARDING_WIRE_CHECKSUM_DOMAIN,
  type ViewerOnboardingBundleV2,
  ViewerOnboardingError,
  type ViewerOnboardingErrorReason,
  type ViewerOnboardingServerIdentityKey,
  verifyViewerOnboardingBundle,
  viewerOnboardingBundleChecksum,
} from "./a1-onboarding.js";
export {
  type A1BrokerRoute,
  type A1ChatControlKind,
  type A1ChatKeys,
  type A1ContentKind,
  type A1Direction,
  type A1EncryptedFrameV2,
  type A1FrameHeaderV2,
  type A1MetaKind,
  type A1Plane,
  type A1RecordKind,
  type A1RouteKind,
  type A1SealedFrameV2,
  type A1ServerControlKeys,
  type A1ServerControlKind,
  A1WireError,
  a1AttemptHeaderDigest,
  a1AuthenticatedPartDigest,
  a1CanonicalMessageDigest,
  a1HostSignaturePayload,
  a1HostSignedRecordDigest,
  a1PlaneForKind,
  a1TransportFrameDigest,
  assertA1FrameMatchesRoute,
  canonicalA1Aad,
  canonicalA1BrokerRouteAddressPreimage,
  canonicalA1BrokerRouteIdPreimage,
  canonicalA1StableLogicalHeader,
  deriveA1BrokerRouteId,
  deriveA1ChatAddress,
  deriveA1ChatKeys,
  deriveA1ChatToken,
  deriveA1MessageKey,
  deriveA1ScopeAddress,
  deriveA1ScopeToken,
  deriveA1ServerControlAddress,
  deriveA1ServerControlKeys,
  deriveA1ServerControlToken,
  encodeA1EncryptedFrameV2,
  encodeA1EncryptedFrameV2Bytes,
  normalizedA1TransportFrameBytes,
  openA1FramePart,
  parseA1EncryptedFrameV2,
  sealA1FramePartWith,
} from "./a1-wire.js";
export { canonicalAad, type Dir, type FrameHeader } from "./aad.js";
export { AeadError, type Frame, open, seal } from "./aead.js";
export { base64urlDecode, base64urlEncode } from "./base64url.js";
export { concatBytes, fromHex, sha256, timingSafeEqual, toHex, utf8 } from "./bytes.js";
export { CanonicalWriter, canonicalByteSnapshot } from "./canonical.js";
export { normalizeChecksum } from "./checksum.js";
export {
  ChunkError,
  type ChunkHeader,
  openChunked,
  sealChunked,
  splitPlaintext,
} from "./chunk.js";
export {
  decodeHandoffBox,
  encodeHandoffBox,
  formatOtk,
  generateOtk,
  type HandoffBox,
  HandoffError,
  type HandoffErrorReason,
  handoffClaimProof,
  handoffId,
  handoffProofHash,
  openHandoff,
  parseOtk,
  sealHandoff,
} from "./handoff.js";
export { hkdfExpand, hkdfExtract } from "./hkdf.js";
export { deriveIdentity, deriveSessionKey, type Identity } from "./kdf.js";
export { formatPass, PassError, type PassErrorReason, parsePass } from "./pass.js";
export {
  formatSecret,
  generateSecret,
  parseSecret,
  SecretError,
  type SecretErrorReason,
} from "./secret.js";
export { busToken, identityHex, sessionToken } from "./tokens.js";
export { decodeFrame, encodeFrame, WireError, type WireFrame } from "./wire.js";
