import { gunzipSync } from "node:zlib";
import { NativeConnection, Worker, type WorkflowBundle } from "@temporalio/worker";
import { temporalConfig } from "./connection";
import { WORKFLOW_BUNDLE_GZIP_B64 } from "./workflow-bundle.generated";

// Shared bootstrap for the relayChannel worker, used by BOTH callers so they can't drift:
//   • temporal/worker.ts          — the standalone worker SERVICE (runs forever; dev + self-hosted).
//   • app/api/temporal/drain      — the Vercel keep-warm route (runs a BOUNDED window, re-armed by a
//                                   cron) because a serverless function can't poll a queue 24/7.
//
// The workflow bundle is PRE-BUILT at commit time (workflow-bundle.generated.ts, regenerated by
// scripts/gen-workflow-bundle.mjs) rather than bundled at runtime. Two reasons: (1) Next emits
// `new URL("./workflows.ts", import.meta.url)` as a LONE asset, so a runtime bundleWorkflowCode of
// it can't resolve its `./names` import on Vercel — the route would 500; (2) it keeps the heavy
// workflow bundler out of the function. A drift test asserts the committed bundle matches source.

let cachedBundle: WorkflowBundle | undefined;

/** The relayChannel workflow code (pre-bundled, gunzipped once and cached). Exposed so the drain
 *  route's `?selftest=1` can confirm the bundle loads in-function without touching a cluster. */
export function relayWorkflowBundle(): WorkflowBundle {
  if (cachedBundle === undefined) {
    const code = gunzipSync(Buffer.from(WORKFLOW_BUNDLE_GZIP_B64, "base64")).toString("utf8");
    cachedBundle = { code };
  }
  return cachedBundle;
}

export interface RelayWorker {
  worker: Worker;
  connection: NativeConnection;
  namespace: string;
  taskQueue: string;
  address: string;
}

/** Connect + build a relayChannel Worker (not yet running). Caller drives worker.run()/shutdown(). */
export async function createRelayWorker(): Promise<RelayWorker> {
  const { namespace, taskQueue, connection: opts } = temporalConfig();
  const connection = await NativeConnection.connect(opts);
  try {
    const worker = await Worker.create({
      connection,
      namespace,
      taskQueue,
      workflowBundle: relayWorkflowBundle(),
    });
    return { worker, connection, namespace, taskQueue, address: opts.address };
  } catch (e) {
    // Don't leak the gRPC connection if Worker.create fails (bad bundle, auth, unreachable cluster).
    await connection.close().catch(() => {});
    throw e;
  }
}

export interface DrainResult {
  ran: true;
  windowMs: number;
  namespace: string;
  taskQueue: string;
  address: string;
}

/** Run the relayChannel worker for ~windowMs, then drain in-flight tasks and close. Resolves once the
 *  worker has fully shut down. The window is sized UNDER the function's maxDuration and OVER the cron
 *  interval so successive invocations overlap (there's never a moment with no poller). worker.run()
 *  resolves after shutdown()'s graceful drain completes. */
export async function runRelayWorkerFor(windowMs: number): Promise<DrainResult> {
  const { worker, connection, namespace, taskQueue, address } = await createRelayWorker();
  const timer = setTimeout(() => {
    // shutdown() can throw if the worker hasn't reached RUNNING yet (a very small window); swallow it
    // — worker.run() below still settles and the finally closes the connection.
    try {
      worker.shutdown();
    } catch {
      // already stopping / not started — nothing to do
    }
  }, windowMs);
  if (typeof timer.unref === "function") timer.unref();
  try {
    await worker.run(); // resolves when the timer-triggered shutdown's graceful drain finishes
  } finally {
    clearTimeout(timer);
    await connection.close().catch(() => {});
  }
  return { ran: true, windowMs, namespace, taskQueue, address };
}
